# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Automated - Website

on:
  push:
    branches:
      - main
    tags:
      - "apache-arrow-adbc-*"
      - "!apache-arrow-adbc-*-rc*"
  workflow_dispatch: {}

# Ensure concurrent builds don't stomp on each other
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: false

defaults:
  run:
    # 'bash' will expand to -eo pipefail
    shell: bash

jobs:
  build:
    name: "Build Website"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Build
        run: |
          docker compose run docs
      - name: Archive docs
        uses: actions/upload-artifact@v5
        with:
          name: docs
          retention-days: 2
          path: |
            docs/build/html

  publish:
    name: "Publish Website"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          path: site
          # NOTE: needed to push at the end
          persist-credentials: true
          ref: asf-site
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          path: scripts
          persist-credentials: false
      - name: Download docs
        uses: actions/download-artifact@v5
        with:
          name: docs
          path: temp
      # To use pip below, we need to install our own Python; the system Python's
      # pip won't let us install packages without a scary flag.
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Build
        run: |
          pip install sphobjinv
          ./scripts/ci/scripts/website_build.sh "$(pwd)/scripts" "$(pwd)/site" "$(pwd)/temp"
      - name: Push changes to asf-site branch
        run: |
          cd site
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "publish documentation" --allow-empty
          git push origin asf-site:asf-site
